run: 
    mode: autoline
save: 
    en: True
    pub: 
        prefix: demo_full
        subdir: test
gpt: 
    model: 4t
autoline: 
    probset: 
        path: data/HDLBits/HDLBits_data.jsonl
        mutant_path: data/HDLBits/HDLBits_data_mutants.jsonl
    promptscript: pychecker
    timeout: 40